server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #org.h2.Driver
    #url: jdbc:h2:file:./blogs.db
    url: jdbc:mysql://localhost:3306/blog?useSSL=false
    username: bloguser
    password: blogpass
  jpa:
    generate-ddl: on
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
